services:
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka_container
    restart: unless-stopped
    ports:
      - "9092:9092"
    env_file:
      - kafka\.env
    volumes:
      - ./kafka/data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui_container
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  mongo-processor:
    image: mongo:8.0
    container_name: mongo-processor
    env_file:
      - processor/.env
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./processor/mongo:/data/processor/mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongo-notifier:
    image: mongo:8.0
    container_name: mongo-notifier
    env_file:
      - notifier/.env
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ./notifier/mongo:/data/notifier/mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  ingestor:
    build: ingestor/.
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped
    container_name: ingestor
    depends_on:
      mongo-processor:
        condition: service_healthy

  notifier:
    build: notifier/.
    ports:
    - "${APP_PORT:-8000}:8000"
    restart: unless-stopped
    container_name: notifier
    depends_on:
      mongo-notifier:
        condition: service_healthy

  processor:
    build: processor/.
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped
    container_name: processor